### ISSUE TITLE
burpWhatsapp.py how do I execute

### ISSUE THREAD

**Issue by Rhomennik** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#3]
I CAN NOT understand this part of the manual, where do I put the burpWhatsapp.py? And then how do I execute?

Second you have to add the file burpWhatsapp.py to your burpsuit extensions.

obs: Do you have a telegram group or something like that?

**Comment by romanzaikin** [comment]
Read about burpsuit proxy... our tool is extension and not a tool by it's own...

**Comment by baptx** [comment]
@Rhomennik I shared a standalone Python script (to use with Python 2) that you can use without Burp Suite: https://pastebin.com/hNBeEqgv
It is also possible to call it from an open source proxy like mitmproxy and the tool mitmdump.
However I was not able to encrypt some data, for example when loading or sending messages in a group: https://github.com/sigalor/whatsapp-web-reveng/issues/247#issuecomment-873221162
I also tested with the file https://github.com/romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint/blob/master/helper/libs/whatsapp_write.py and the following code for the encryptBinary function of my script but it is not working either to encrypt sent or received messages in a group (`ValueError: chr() arg not in range(256)`), it only works with simple messages like in the example below:
```
originalMessage = b'XXX' # encrypted
message = ['action', {'epoch': '1', 'type': 'set'}, [['presence', {'type': 'unavailable'}, None]]] #decrypted

messageSplit = originalMessage.split(",", 1)
content = messageSplit[1]

content = content[2:] # for sent messages (remove first 2 bytes)
decryptedData = AESDecrypt(encKey, content[32:])

char_diff = len(str(message)) - len(str(message).replace("u'","'"))
stream = WhatsAppWriter(decryptedData, char_diff)
stream.write_node(message)
processedData = stream.get_data()

enc = AESEncrypt(encKey, processedData)
encryptedData = HmacSha256(macKey, enc) + enc; # this may need padding to 64 byte boundary
return encryptedData
```

I also don't understand why to use the WhatsAppWriter function of this project, we need 3 variables decryptedData, char_diff and message. On the other project, we just need the message. I did not see it written in the readme of this project but I guess functions like WhatsAppWriter are based on the libraries of the other project.
@romanzaikin Any idea how to make the script work to encrypt sent or received messages in a group? I guess the problem is also present on the Burp Extension since it is using WhatsAppWriter.
