### ISSUE TITLE
Problem: "Bad message, can't decript the incoming message"

### ISSUE THREAD

**Issue by 0ptimusPr1m3** [romanzaikin/BurpExtension-WhatsApp-Decryption-CheckPoint#30]
I am Getting the error message in Burp, Can't decrypt message. Keys are correct and ref is also correct

**Comment by thiru112** [comment]
@0ptimusPr1m3 Is it incoming message or outgoing message 
pls state it z

**Comment by thiru112** [comment]
@0ptimusPr1m3 I think your keys might be wrong or try again with some other message , because my message encryption and decryption **works perfectly**

Reasons might be (troubleshooting options)
- keys might be wrong.
- Not converted to **base 64 encode(press Ctrl+B)**
- What your trying to decrypt might not be a message 

I can help you further if u send some screenshot

**Comment by silverar** [comment]
> I am Getting the error message in Burp, Can't decrypt message. Keys are correct and ref is also correct

what was the problem ? i have the same issue , i think if the keys are wrong i will not be able to connect. i got OK message when i click connect
